export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const FETCH_INGREDIENTS = 'FETCH_INGREDIENTS';

export const PURCHASE_START = 'PURCHASE_START';
export const PURCHASE_FAIL = 'PURCHASE_FAIL';
export const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS';

