export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const FETCH_INGREDIENTS = 'FETCH_INGREDIENTS';

export const PURCHASE_START = 'PURCHASE_START';
export const PURCHASE_FAIL = 'PURCHASE_FAIL';
export const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS';
export const PURCHASED_RESET = 'PURCHASED_RESET';

export const FETCHING_ORDERS_START = 'FETCHING_ORDERS_START';
export const FETCHING_ORDERS_SUCCESS = 'FETCHING_ORDERS_SUCCESS';
export const FETCHING_ORDERS_FAIL = 'FETCHING_ORDERS_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_PATH_REDIRECT = 'SET_PATH_REDIRECT';
